sudo: required
services:
  - docker

script:
  - docker build -t nbtadmin/sprout-api-nginx ./nginx
  - docker build -t nbtadmin/sprout-api ./api

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub

  - docker push nbtadmin/sprout-api-nginx
  - docker push nbtadmin/sprout-api

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: SproutDev
  env: SproutDevWebApp
  bucket_name: elasticbeanstalk-us-east-2-780000951144
  bucket_path: nbt-dev-env
  on:
    branch: develop
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
